apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: rage-swipelab-co-tls
spec:
  secretName: rage-swipelab-co
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: rage.swipelab.co
  dnsNames:
    - rage.swipelab.co
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - rage.swipelab.co